### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by antoniocastanheira** [institutotim/zup-android-cidadao#2]
- [ ] Primeiro acesso ao app, não ocorre geolocalização após permissionamento e em seguida o aplicativo quebra;
- [ ] Câmera não funciona no Android 7;
- [ ] Upload não funciona no Android 7;
- [ ] Filtros de status não funcionam;
- [ ] Filtros de períodos não funcionam;
- [ ] Botão de geo localizar as vezes para no oceano;

**Comment by photonauta35** [comment]
Detalhes, quero detalhes...

**Comment by GustavoVS** [comment]
![image](https://cloud.githubusercontent.com/assets/7750643/26509890/3bb9095a-4231-11e7-89ee-533da11c5c78.png)

**Comment by vitor-kato** [comment]
![site_decal_bugs](https://cloud.githubusercontent.com/assets/21978887/26510353/575841b0-4233-11e7-9c5f-ae2681229476.jpg)

**Comment by intrepidocabral** [comment]
feito! Realizar review e fazer merge com master. @vitor-kato

**Comment by vitor-kato** [comment]
Antigo Master salvo se houver necessidade de futuras consultas no branch: **master_legacy**
Branch Crashlytics que era o mais estável e atual. Movido como **master**
